version: '2.1'

services:
  #service 1: mysql database image creation
  db:
    image: mysql:5.7.6
    container_name: mysql-db
    ports:
      - "3307:3307"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=spring
      - MYSQL_DATABASE=onlineshop
      - MYSQL_USER=spring
      - MYSQL_PASSWORD=spring
    volumes:
#      - data_volume:/var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  # service 2: online store service
  service:
    image: service
    container_name: service-app
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - ./migration:/usr/init-data/
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/onlineshop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: spring
      SPRINT_DATASOURCE_INITIALIZATION-MODE: always
      SPRING_DATASOURCE_DATA: /usr/init-data/data.sql
      SPRING_DATA_JPA-DATASOURCE-INITIALIZATION: true
      SPRING_SQL_INIT_MODE: always
